services:
  # Service 1: The Database
  db:
    # imagename:version
    image: postgres:latest
    container_name: workshop_postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      # Mapping a Named Volume for persistence
      # outside:container
      - ./data:/var/lib/postgresql/data
    ports:
      # outside:container
      - "7732:5432"

  # Service 2: The UI Tool
  adminer:
    image: adminer
    container_name: workshop_adminer
    restart: always
    ports:
      - "7780:8080"
    depends_on:
      - db
